test: LoginSessionManager 테스트 코드 제작
kaestro/ChatApplication pull request #27
Opened 2024-03-22 07:38 UTC by TLOWAC

<img width="346" alt="image" src="https://github.com/kaestro/ChatApplication/assets/58043975/19e06bb0-1774-4958-a9f9-2d1003907fd9">

2024-03-22 07:40 UTC, kaestro commented on myapp/internal/session/LoginSessionManager_test.go
> +		t := s.T()
tab에 대해서는 통일해서 사용했으면 좋을 것 같습니다

2024-03-22 07:42 UTC, kaestro commented on myapp/internal/session/LoginSessionManager_test.go
> +	s.redisClient = redis.NewClient(&redis.Options{
실제 연결을 사용하고 계신데, 연구로 올리셨던 자료에 해당하는 연결을 github actions에 띄우거나 docker test형태로 띄우지 않으면 현재는 아마 github actions를 통과하지 못할 것 같아요.

2024-03-22 07:44 UTC, kaestro requested changes
tab의 형식이 일정하지 않은 것하고, githuub actions를 고려한 코드 변경 혹은 github actions 변경이 선행돼야할 것 같습니다

2024-03-22 07:45 UTC, kaestro commented
> ### 작업 내용
> LoginSessionManager_test.go 의 테스트 코드를 작업 하였습니다.
> 
> ### 테스트 동작 결과 화면
> <img alt="image" width="346" src="https://private-user-images.githubusercontent.com/58043975/315924196-19e06bb0-1774-4958-a9f9-2d1003907fd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTM3NzYsIm5iZiI6MTcxMTA5MzQ3NiwicGF0aCI6Ii81ODA0Mzk3NS8zMTU5MjQxOTYtMTllMDZiYjAtMTc3NC00OTU4LWE5ZjktMmQxMDAzOTA3ZmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA3NDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NmQ1MzI2YmUyYmIwMzhmMjI2NjRhNDI5YzY2ZDdlNmNhZWQzZjMwNDFiNDJkYjlhMjFiMzJjODM1ZGViNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xgzlCbUxVbKnhY-gXCed1L6tg1_QXzIEfmZx8h108ZQ">

이건 제가 뭘 잘못 알고 있는 것 같은데, 이건 실제 redis 연결을 생성하는데 github actions 테스트가 왜 통과 돼고 있는건가요? 신기하네요

2024-03-22 07:52 UTC, TLOWAC commented on myapp/internal/session/LoginSessionManager_test.go
> +		t := s.T()
로컬에서랑 푸쉬한 코드의 탭이 다르게 보이는 현상이 있네요
수정하겠습니다!

2024-03-22 07:55 UTC, TLOWAC commented on myapp/internal/session/LoginSessionManager_test.go
> +	s.redisClient = redis.NewClient(&redis.Options{
네 맞습니다 :)
우선 github action 에 redis container 를 동작시키는 가정하에 작성하였고, 추후 mock 사용으로 의견이 통일되면 컨벤션에 맞춰 mockRedis 을 사용하는 방식으로 리팩토링 진행 할 수 있도록 하겠습니다.

이번 회의때 스펙을 정하고 가면 좋을것 같습니다.

2024-03-22 18:26 UTC, kaestro approved these changes
LGTM
그런데 어떻게 고치신건가요? 궁금하네요ㅋㅋ

2024-03-23 05:09 UTC, TLOWAC commented
> LGTM 그런데 어떻게 고치신건가요? 궁금하네요ㅋㅋ

테스트 코드 파일 위치에서 `go fmt` 하니까 스타일이 정상적으로 수정이 되더라구요 ㅋㅋㅋㅋ
https://stackoverflow.com/questions/19094704/indentation-in-go-tabs-or-spaces

2024-03-23 11:54 UTC, kaestro commented
이런거 보면 진짜 go가 언어가 엄청 편하고 좋긴 한거 같은데 ㅋㅋ

2024-03-23 11:54 UTC, merged